project_id = "jeyvjvofrsyqrefzelhg"

[functions.identify-food]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.generate-weekly-plan]
verify_jwt = false

[functions.voice-assistant]
verify_jwt = false

[functions.start-trial]
verify_jwt = false

[functions.generate-recipe]
verify_jwt = false
